In [ ]:
pip install google-api-python-client pandas spacy tensorflow keras

In [ ]:
from googleapiclient.discovery import build
import pandas as pd

# Replace with your API key (get from Google Cloud Console)
API_KEY = "AIzaSyAge4lohjY8W-hDJRmbx9B7rTMlI7qbUHY"
VIDEO_ID = "ez1cn8d28_8"  # e.g., "dQw4w9WgXcQ"

youtube = build('youtube', 'v3', developerKey=API_KEY)

comments = []
next_page_token = None

while True:
    response = youtube.commentThreads().list(
        part='snippet',
        videoId=VIDEO_ID,
        maxResults=1000,
        pageToken=next_page_token
    ).execute()

    for item in response['items']:
        comment = item['snippet']['topLevelComment']['snippet']['textDisplay']
        comments.append(comment)

    next_page_token = response.get('nextPageToken')
    if not next_page_token:
        break

df = pd.DataFrame(comments, columns=['comment'])
print(df.head())


                                             comment
0  I suspect it was at a Black march. They&#39;d ...
1  WHY YOU INSELT REGION YOU KNOW YOU WILL BE KILLED
2  <a href="https://www.youtube.com/watch?v=ez1cn...
3  Thank you Niko. THIS is true journalism keep i...
4                                         Crazy loot


In [ ]:
df.to_csv('comments.csv',columns=['comment'] ,index=False)

In [ ]:
import pandas as pd
df = pd.read_csv(r"/content/comments.csv")

In [ ]:
df.head()

comment  \
0  I suspect it was at a Black march. They&#39;d ...   
1  WHY YOU INSELT REGION YOU KNOW YOU WILL BE KILLED   
2  <a href="https://www.youtube.com/watch?v=ez1cn...   
3  Thank you Niko. THIS is true journalism keep i...   
4                                         Crazy loot   

                                       clean_comment  \
0  i suspect it was at a black march theyd say th...   
1  why you inselt region you know you will be killed   
2  a href i love these homeless chaps had the mos...   
3  thank you niko this is true journalism keep it...   
4                                         crazy loot   

                                              tokens  
0  ['suspect', 'black', 'march', 'd', 'white', 'p...  
1               ['inselt', 'region', 'know', 'kill']  
2      ['href', 'love', 'homeless', 'chap', 'sense']  
3  ['thank', 'niko', 'true', 'journalism', 'peopl...  
4                                  ['crazy', 'loot']

In [ ]:
import spacy
import re

nlp = spacy.load("en_core_web_sm")

def clean_text(text):
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = text.lower().strip()
    return text

def tokenize_spacy(text):
    doc = nlp(text)
    return [token.lemma_ for token in doc if not token.is_stop]

df['clean_comment'] = df['comment'].apply(clean_text)
df['tokens'] = df['clean_comment'].apply(tokenize_spacy)
print(df[['comment', 'tokens']].head())


                                             comment  \
0  I suspect it was at a Black march. They&#39;d ...   
1  WHY YOU INSELT REGION YOU KNOW YOU WILL BE KILLED   
2  <a href="https://www.youtube.com/watch?v=ez1cn...   
3  Thank you Niko. THIS is true journalism keep i...   
4                                         Crazy loot   

                                              tokens  
0          [suspect, black, march, d, white, people]  
1                       [inselt, region, know, kill]  
2                [href, love, homeless, chap, sense]  
3  [thank, niko, true, journalism, people, love, ...  
4                                      [crazy, loot]  


In [ ]:
df.to_csv('comments.csv',index=False)

In [ ]:
import pandas as pd
df = pd.read_csv(r"/content/comments.csv")

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(df['tokens'])

X = tokenizer.texts_to_sequences(df['tokens'])
X = pad_sequences(X, maxlen=50)  # truncate/pad to uniform length

In [ ]:
X

array([[   0,    0,    0, ...,  109,   10,    2],
       [   0,    0,    0, ..., 1923,   21,  106],
       [   0,    0,    0, ...,  998, 3099,  336],
       ...,
       [   0,    0,    0, ..., 2472,   79,   82],
       [   0,    0,    0, ...,  977,   33,  990],
       [   0,    0,    0, ...,    0,    0,  342]], dtype=int32)

In [ ]:
from tensorflow.keras.utils import to_categorical
from textblob import TextBlob

def get_sentiment(text):
   # Ensure text is a string before passing to TextBlob
   if not isinstance(text, str):
        text = str(text) # Convert non-string values to string

   if TextBlob(text).sentiment.polarity > 0:
     return 1
   elif TextBlob(text).sentiment.polarity < 0:
    return -1
   else:
    return 0

df['sentiment'] = df["comment"].apply(get_sentiment)

In [ ]:
TextBlob('i hate you').sentiment.polarity

-0.8

In [ ]:
y =df['sentiment']
y

0       -1
1       -1
2        1
3        1
4       -1
        ..
21164    1
21165    1
21166    0
21167    1
21168    0
Name: sentiment, Length: 21169, dtype: int64

In [ ]:
y.value_counts()

sentiment
1    7726
2    7335
0    6108
Name: count, dtype: int64

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical

# Shift labels
y = y.replace({-1: 0, 0: 1, 1: 2})
y_cat = to_categorical(y, num_classes=3)

# Model architecture
model = Sequential([
    Embedding(input_dim=5000, output_dim=128, input_length=50),
    LSTM(128, dropout=0.3, recurrent_dropout=0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')   # 3-class output
])

# Compile and train
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y_cat, epochs=5, batch_size=32, validation_split=0.2)


Epoch 1/5


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


530/530 ━━━━━━━━━━━━━━━━━━━━ 79s 139ms/step - accuracy: 0.7339 - loss: 0.5767 - val_accuracy: 0.8857 - val_loss: 0.2773
Epoch 2/5
530/530 ━━━━━━━━━━━━━━━━━━━━ 79s 134ms/step - accuracy: 0.8947 - loss: 0.2683 - val_accuracy: 0.8966 - val_loss: 0.2616
Epoch 3/5
530/530 ━━━━━━━━━━━━━━━━━━━━ 68s 129ms/step - accuracy: 0.9160 - loss: 0.2135 - val_accuracy: 0.8968 - val_loss: 0.2713
Epoch 4/5
530/530 ━━━━━━━━━━━━━━━━━━━━ 70s 131ms/step - accuracy: 0.9355 - loss: 0.1738 - val_accuracy: 0.8876 - val_loss: 0.3054
Epoch 5/5
530/530 ━━━━━━━━━━━━━━━━━━━━ 68s 129ms/step - accuracy: 0.9483 - loss: 0.1414 - val_accuracy: 0.8793 - val_loss: 0.3328


In [ ]:
loss, acc = model.evaluate(X1, y_cat)
print(f" Model Accuracy: {acc:.2f}")

662/662 ━━━━━━━━━━━━━━━━━━━━ 80s 120ms/step - accuracy: 0.7172 - loss: 1.3278
 Model Accuracy: 0.71


In [ ]:
import numpy as np
import re

def predict_comment(comment):
    cleaned = clean_text(comment)
    tokens = tokenize_spacy(cleaned)
    seq = get_spacy_embeddings(tokens)
    seq = tokenizer.texts_to_sequences([seq])
    pad = pad_sequences(seq, maxlen=50)
    pred = model.predict(pad)
    label = np.argmax(pred)

    mapping = {0: "Negative 😞", 1: "Neutral 😐", 2: "Positive 😀"}
    return mapping[label]

print(predict_comment("good"))
print(predict_comment("This is the  thing ever"))


AttributeError: 'numpy.ndarray' object has no attribute 'lower'

In [ ]:
# Save model after training
model.save('model.keras')

In [ ]:
y_cat

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [ ]:
import spacy
import re
import pickle

class TextPreprocessor:
    def __init__(self):
        self.nlp = spacy.load("en_core_web_sm")

    def clean_text(self, text):
        text = re.sub(r"http\S+|www\S+", "", text)
        text = re.sub(r"[^a-zA-Z\s]", "", text)
        text = text.lower().strip()
        return text

    def tokenize_spacy(self, text):
        doc = self.nlp(text)
        return [token.lemma_ for token in doc if not token.is_stop]

    def transform(self, texts):
        cleaned = [self.clean_text(t) for t in texts]
        tokens = [" ".join(self.tokenize_spacy(t)) for t in cleaned]
        return tokens

preprocessor = TextPreprocessor()

# Save the object (this stores only function references, not the full spaCy model)
# Save tokenizer
with open('preprocessor.pkl', 'wb') as f:
    pickle.dump(preprocessor, f)

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(df['tokens'])

X = tokenizer.texts_to_sequences(df['tokens'])
X = pad_sequences(X, maxlen=50)  # truncate/pad to uniform length

# Save tokenizer
with open('tokenizer.pkl', 'wb') as f:
    pickle.dump(tokenizer, f)

In [ ]:
import tensorflow as tf
import pickle

# Load Keras model
model = tf.keras.models.load_model("model.keras")

# Wrapper for lightweight predict
class SimpleModel:
    def __init__(self, keras_model):
        self.keras_model = keras_model

    def predict(self, X):
        preds = self.keras_model.predict(X)
        return preds.argmax(axis=1)  # return label indices

# Create wrapper instance
simple_model = SimpleModel(model)

# Save as pickle
with open("simple_model.pkl", "wb") as f:
    pickle.dump(simple_model, f)

print("✅ simple_model.pkl saved successfully!")


✅ simple_model.pkl saved successfully!


/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 12 variables whereas the saved optimizer has 22 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [ ]:
!pip install spacy
!python -m spacy download en_core_web_md

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 48.5 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
def clean_text(text):
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = text.lower().strip()
    return text

def tokenize_spacy(text):
    doc = nlp(text)
    return [token.lemma_ for token in doc if not token.is_stop]

In [ ]:
import spacy
import numpy as np
import pandas as pd

# Load spaCy model with pretrained word vectors
nlp = spacy.load("en_core_web_md")

# Convert text → embeddings
def get_spacy_embeddings(texts):
    embeddings = []
    for doc in nlp.pipe(texts, disable=["ner", "parser"]):  # faster processing
        embeddings.append(doc.vector)  # 300-dim vector for each sentence
    return np.array(embeddings)

X1 = get_spacy_embeddings(df['tokens'])

print("Shape of embedding matrix:", X1.shape)
print("First vector (truncated):", X1[0][:10])

with open("spacy_embeddings.pkl", "wb") as f:
    pickle.dump(X1, f)

Shape of embedding matrix: (21169, 300)
First vector (truncated): [-0.66527456  0.22954835 -0.13709067 -0.13440016  0.20841114 -0.04640345
 -0.05352061 -0.22951992  0.09705013  0.9481037 ]


In [ ]:
X1

array([[-0.66527456,  0.22954835, -0.13709067, ..., -0.09595276,
        -0.3154019 ,  0.07035875],
       [-0.6411    ,  0.26709294, -0.16190764, ..., -0.08573648,
        -0.28194922,  0.06009807],
       [-0.65320665,  0.26571643, -0.1792623 , ..., -0.07826124,
        -0.3539871 ,  0.15329774],
       ...,
       [-0.6403885 ,  0.15632845, -0.16046245, ...,  0.04836538,
        -0.41245878,  0.1759897 ],
       [-0.65328056,  0.2943666 , -0.08981594, ..., -0.06054613,
        -0.34981114,  0.08664352],
       [-0.640268  ,  0.2181484 ,  0.04298281, ..., -0.0247644 ,
        -0.4112362 ,  0.09585161]], dtype=float32)